//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/InputControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControl"",
    ""maps"": [
        {
            ""name"": ""KeyCode"",
            ""id"": ""6263bfe5-b39a-417f-b10c-c306e8269ac1"",
            ""actions"": [
                {
                    ""name"": ""Any Key"",
                    ""type"": ""Button"",
                    ""id"": ""27023462-7d6a-4d8e-af34-ee50c9f4b7d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a3fbc440-c5b2-4652-a8ec-b98049cedfe0"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Any Key"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // KeyCode
        m_KeyCode = asset.FindActionMap("KeyCode", throwIfNotFound: true);
        m_KeyCode_AnyKey = m_KeyCode.FindAction("Any Key", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // KeyCode
    private readonly InputActionMap m_KeyCode;
    private List<IKeyCodeActions> m_KeyCodeActionsCallbackInterfaces = new List<IKeyCodeActions>();
    private readonly InputAction m_KeyCode_AnyKey;
    public struct KeyCodeActions
    {
        private @InputControl m_Wrapper;
        public KeyCodeActions(@InputControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @AnyKey => m_Wrapper.m_KeyCode_AnyKey;
        public InputActionMap Get() { return m_Wrapper.m_KeyCode; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyCodeActions set) { return set.Get(); }
        public void AddCallbacks(IKeyCodeActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyCodeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyCodeActionsCallbackInterfaces.Add(instance);
            @AnyKey.started += instance.OnAnyKey;
            @AnyKey.performed += instance.OnAnyKey;
            @AnyKey.canceled += instance.OnAnyKey;
        }

        private void UnregisterCallbacks(IKeyCodeActions instance)
        {
            @AnyKey.started -= instance.OnAnyKey;
            @AnyKey.performed -= instance.OnAnyKey;
            @AnyKey.canceled -= instance.OnAnyKey;
        }

        public void RemoveCallbacks(IKeyCodeActions instance)
        {
            if (m_Wrapper.m_KeyCodeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyCodeActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyCodeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyCodeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyCodeActions @KeyCode => new KeyCodeActions(this);
    public interface IKeyCodeActions
    {
        void OnAnyKey(InputAction.CallbackContext context);
    }
}
